### ISSUE TITLE
Add stack outputs and stack tags to webhook request payload

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/console-requests#231]
At the end of a Pulumi update, it would be useful for the webhook request payload to include the (non secret) stack outputs and the stack tags.

The outputs could include such things as Cloudfront distribution URLS to be passed onto another service.

**Comment by EvanBoyle** [comment]
We may not want to do this due to the potential size of the payload. Instead, this scenario can be accomplished by querying for stack tags and stack outputs.

Here's some sample code that looks up tags in the context of a webhook.

https://github.com/pulumi/deploy-demos/blob/main/pulumi-programs/ttl-stacks/index.ts#L183-L204
