### ISSUE TITLE
Team Access Token: `pulumi whoami -v` should return the team name as the User

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/console-requests#236]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When using a Team Access token to login to Pulumi, `pulumi whoam -v` currently returns:
```
User: ORGNAME
Organizations: ORGNAME
Backend URL: https://app.pulumi.com/ORGNAME
```

The `User` field should reflect the name of the Team that the Team Access Token is associated with.

### Affected area/feature

`pulumi whoami -v`

**Comment by Frassle** [comment]
We're dependent on what `/api/user` returns from the cloud service for this.

cc @EvanBoyle does it make sense for `/api/user` to return the team name rather than the orgname for team access token sessions?

**Comment by Danielkiss9** [comment]
In my opinion this ^ will be very helpful. 
as of today we are using 4 different access tokens (1 for every team that uses the access token) and when trying to access the whoami -v we cant really know which team we're working on at the moment.

**Comment by djgrove** [comment]
I've transferred this issue to `pulumi-cloud-requests` since this affects the Pulumi Cloud APIs.

I agree that something should definitely be returned to indicate that the token is scoped to a given team. We would probably still like to preserve that the user is acting within the context of an org--for example, if an org `foobar` had a team `djgrove`, it would be potentially misleading to say that the User is `djgrove`.

Certainly open to input on what to return for the user, but I would lean towards something along the lines of:
```
User: ORGNAME (via team token 'TOKENNAME' for team TEAMNAME)
```

The important requirement is that I'd assume we want all three of org name, team name, and token name to be surfaced in the result. Would this meet your needs @Danielkiss9? Is the name of the token itself helpful here in addition to the team it is scoped to?

**Comment by djgrove** [comment]
A better solution is probably to treat the token information as first-class. That is, to return two additional properties with the token:
```
User: <unchanged>
Organizations: <unchanged>
Token type: <organization: "OrgName"> | <team: "TeamName"> | <personal>
Token name: "TokenName" # if applicable
```

This solution would require changes to the Pulumi CLI, and thus would require upgrading to take effect.

**Comment by Frassle** [comment]
Happy to sort out those CLI changes if the API is updated to return that info.

**Comment by Danielkiss9** [comment]
@djgrove Would be absoloutly great. Thanks!

**Comment by Frassle** [comment]
I can pick up the CLI side for this
