### ISSUE TITLE
Add ability to pause deployments on a stack

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/console-requests#247]
- [x] Design doc reviewed with the team
- [ ] Project plan reviewed with @EvanBoyle 

It would be nice if users could call an API and/or press a button in the console to stop deployments from executing on a stack. Would probably be nice to offer two different modes (1) calls to create deployment (or other triggers) will fail, or (2) deployments will queue and execute sequentially once the stack is un-paused. This could be useful for many situations such as dealing with an outage or livesite event where you want to stop automated updates until manual remediation is complete. Might also be worth considering how queueing behaves. We could offer options that allow users to queue all submitted deployments, or skip all intermediate deployments as suggested via https://github.com/pulumi/pulumi-cloud-requests/issues/136

**Comment by EvanBoyle** [comment]
We need an org-level toggle that admins can control, with a stack-level toggle that stack writers can control.

**Comment by aaijazi** [comment]
A few UX focused questions I have:

1. If we add toggle at both the stack and the org level to pause all future deployments - do we have any thoughts on what that might look like or where it might go? For the org level toggle, I could imagine it going into the Permissions box of Access Management (e.g., "Pause deployments for all organization members"). For the stack level, if we put it in the Deployments settings page, it feels like that might be a bit too hidden. Do we want to surface the pause button in a completely different place? 
2. I think we probably want to add some kind of banner with a message or something on the Activities / Deployments tab when deployments are paused, so it's obvious why deployments are not making progress. Otherwise, we would just have a bunch of deployments that are in the "pending" state for a long time and it would look like things hung on the Pulumi side
3. For queuing, I'm inclined to just queuing all submitted deployments, and allow the recently added "skip all intermediate deployments" stack toggle to control that part of the behavior, as opposed to having a setting on each pause.

I'm also planning on submitting an API-only change first, and then add the UI piece afterwards, unless there are objections to that

**Comment by aaijazi** [comment]
Short design doc documenting some of my thinking around this feature: https://docs.google.com/document/d/19pf9iEtuC9WqBwKxrdU9fsIjGfcgunVGlljvJe-Oeqk/edit

**Comment by cleverguy25** [comment]
https://github.com/pulumi/pulumi-service/issues/15248
