### ISSUE TITLE
pulumi bot access in github enterprise/multi-org setup

### ISSUE THREAD

**Issue by stevenolen** [pulumi/console-requests#320]
Hi!

Our organization is beginning a transition of our pulumi repos from a single github org to multiple orgs under an enterprise. The pulumi github app integration does not have an obvious configuration for this access in the cloud interface (once an org is configured for the app, the app does not allow additional orgs to be configured). We appear to be able to have pulumi cloud configured as a third party oauth application policy (which enables github actions to work), but the bot doesn't post comments on pull requests.

Do you have recommendations for the happy-path here?

**Comment by zbuchheit** [comment]
Hi Steve,

I have responded to this in the support ticket you opened. Adding a comment here for visibility.

Thanks!

**Comment by zbuchheit** [comment]
This issue was resolved. The user was able to add another org and install the public GitHub app for each of the orgs. 

The user was able to configure second org, but had to visit https://github.com/apps/pulumi to do so since the ui helpers are no longer available once the app is installed once for an org. 

Closing Issue as resolved.
