### ISSUE TITLE
Organization still archived following subscription activation

### ISSUE THREAD

**Issue by vmehera123** [pulumi/console-requests#454]
We expect to use pulumi after updating the subscription. But still have "archived" org, which cause error: `[409] Conflict: The "orgname" organization does not have an active Pulumi subscription.` while using pulumi cli.

**Comment by caseyyh** [comment]
Hey @vmehera123 , thank you for filing this ticket!

Could you clarify the following?

1. What CLI command were you running?
2. What is the name of your pulumi organization?

From the error log pasted, it looks like the command is assuming that the organization is literally called `orgname`, so wanted to confirm if this is intentional or not. Thanks!
