### ISSUE TITLE
Request: Create a Dedicated Microsoft MS Teams Workflow due to Office 365 Connector deprecation

### ISSUE THREAD

**Issue by notjosse** [pulumi/console-requests#456]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Microsoft announced that by December 2025 they are deprecating the Office 365 Connectors (https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/). This will mean that existing Pulumi Microsoft Teams Webhooks (https://www.pulumi.com/docs/pulumi-cloud/webhooks/?#microsoft-teams-webhooks) that utilize the office 365 connector will no longer be supported.

It would be great if we could have a dedicated Pulumi Workflow in the Microsoft Workflows app so that teams can easily transition from office 365 connectors.

**Comment by justinvp** [comment]
Thanks for the issue @notjosse. Moving this to https://github.com/pulumi/pulumi-cloud-requests for review.

**Comment by sebastianfeduniak** [comment]
Thanks for that.
To shed some more light on this.
After deprecating the Office 365 Connectors, in order to keep ci/cd notification working, I need to 
1) create incoming webhooks with Workflows for Microsoft Teams,
2) configure workflow - my example attached ![Image](https://github.com/user-attachments/assets/54ed242d-9461-4698-876e-a7d48800a55f)

3) post to a channel as an adaptive card to make it more friendly than raw json

it's ugly work. I think you may provide dedicated workflow or at least, dedicated card template in https://adaptivecards.io/samples/

**Comment by nyobe** [comment]
@sebastianfeduniak, are you parsing the [generic json webhook](https://www.pulumi.com/docs/pulumi-cloud/webhooks/?#generic-json-webhooks) for your workflow?

We'll soon be deploying an update to the MS Teams webhook integration so it will start emitting adaptive cards natively. Thankfully this is backwards compatible with the old connector endpoints as well as the new workflow ones. 

(But I wanted to make sure you aren't parsing the old messagecard response format from the MS Teams webhook / give you a heads up that this is imminent, so that your workaround won't break when the update goes out)

**Comment by nyobe** [comment]
The MS teams webhook payload is now compatible with workflow based webhooks
